# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jhamidullah\PycharmProjects\Duplicate_sse\ClientApp\UI\DuplicateView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 361)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 831, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.LocationLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocationLabel.sizePolicy().hasHeightForWidth())
        self.LocationLabel.setSizePolicy(sizePolicy)
        self.LocationLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.LocationLabel.setObjectName("LocationLabel")
        self.verticalLayout.addWidget(self.LocationLabel)
        self.TrgLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.TrgLineEdit.setText("")
        self.TrgLineEdit.setObjectName("TrgLineEdit")
        self.verticalLayout.addWidget(self.TrgLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Enter = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Enter.setObjectName("Enter")
        self.horizontalLayout_2.addWidget(self.Enter)
        self.Redo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Redo.setObjectName("Redo")
        self.horizontalLayout_2.addWidget(self.Redo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(12, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OutputTable = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.OutputTable.setFont(font)
        self.OutputTable.setObjectName("OutputTable")
        self.OutputTable.setColumnCount(3)
        self.OutputTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        self.OutputTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OutputTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OutputTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.OutputTable)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 27))
        self.menubar.setObjectName("menubar")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFunctions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LocationLabel.setText(_translate("MainWindow", "Location"))
        self.TrgLineEdit.setPlaceholderText(_translate("MainWindow", "TRG-xxxxxxxx"))
        self.Enter.setText(_translate("MainWindow", "Enter"))
        self.Redo.setText(_translate("MainWindow", "Redo"))
        item = self.OutputTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TRGID"))
        item = self.OutputTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "timeStamp"))
        item = self.OutputTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Functions"))
